#!/usr/bin/env python3
"""
gen_emoji.py  --  SceneChat emoji atlas generator
Reads 32x32 PNGs from EMOJI_DIR, packs into a 256x256 BGRA atlas,
outputs emoji_atlas.h for inclusion in the Xbox client.

Usage:  python3 gen_emoji.py  (run on VPS where PNGs live)
        Copy emoji_atlas.h to the Xbox project.
"""

import os, struct
from PIL import Image

EMOJI_DIR   = "/opt/scenechat/emoji"
OUTPUT_H    = "emoji_atlas.h"
ATLAS_W     = 256
ATLAS_H     = 256
EMOJI_SIZE  = 32          # each emoji cell
PER_ROW     = ATLAS_W // EMOJI_SIZE   # 8 per row

# Explicit ordering -- name = filename stem (no .png)
EMOJI_NAMES = [
    "smile","wink","laugh","cry","angry","sad","surprised","thinking",
    "cool","love_face","dead","party","question","thumbs_up","thumbs_down",
    "check","x","alert","heart","fireheart","star","skull","fire",
    "scenechat_sc","scenechat_softmod","scenechat_fire","scenechat_modchip",
    "scenechat_controller_chat","scenechat_ping","scenechat_lobby",
    "scenechat_dpad","scenechat_buttons","scenechat_devbuild",
]

atlas = Image.new("RGBA", (ATLAS_W, ATLAS_H), (0,0,0,0))

found = []
missing = []

for name in EMOJI_NAMES:
    path = os.path.join(EMOJI_DIR, name + ".png")
    if not os.path.exists(path):
        missing.append(name)
        found.append(None)
        continue
    img = Image.open(path).convert("RGBA")
    if img.size != (EMOJI_SIZE, EMOJI_SIZE):
        img = img.resize((EMOJI_SIZE, EMOJI_SIZE), Image.LANCZOS)
    found.append(img)

if missing:
    print(f"[!] Missing: {missing}")

# Pack atlas
for idx, img in enumerate(found):
    if img is None:
        continue
    col = idx % PER_ROW
    row = idx // PER_ROW
    atlas.paste(img, (col * EMOJI_SIZE, row * EMOJI_SIZE))

# Convert to BGRA for XGSwizzleRect
rgba = atlas.tobytes()
bgra = bytearray(len(rgba))
for i in range(0, len(rgba), 4):
    bgra[i+0] = rgba[i+2]   # B
    bgra[i+1] = rgba[i+1]   # G
    bgra[i+2] = rgba[i+0]   # R
    bgra[i+3] = rgba[i+3]   # A

with open(OUTPUT_H, "w") as f:
    f.write("/* Auto-generated by gen_emoji.py -- do not edit */\n")
    f.write("#ifndef EMOJI_ATLAS_H\n#define EMOJI_ATLAS_H\n\n")
    f.write(f"#define EMOJI_ATLAS_W   {ATLAS_W}\n")
    f.write(f"#define EMOJI_ATLAS_H   {ATLAS_H}\n")
    f.write(f"#define EMOJI_CELL_SIZE {EMOJI_SIZE}\n")
    f.write(f"#define EMOJI_PER_ROW   {PER_ROW}\n")
    f.write(f"#define EMOJI_COUNT     {len(EMOJI_NAMES)}\n\n")

    # Name table
    f.write("static const char * const g_emojiNames[EMOJI_COUNT] = {\n")
    for name in EMOJI_NAMES:
        f.write(f'    "{name}",\n')
    f.write("};\n\n")

    # UV rect table: {u0, v0, u1, v1} in 0..1 floats as fixed-point *65536
    f.write("/* UV rects as 16.16 fixed point (divide by 65536.0 for float) */\n")
    f.write("static const int g_emojiUV[EMOJI_COUNT][4] = {\n")
    for idx, name in enumerate(EMOJI_NAMES):
        col = idx % PER_ROW
        row = idx // PER_ROW
        u0 = (col * EMOJI_SIZE) / ATLAS_W
        v0 = (row * EMOJI_SIZE) / ATLAS_H
        u1 = u0 + EMOJI_SIZE / ATLAS_W
        v1 = v0 + EMOJI_SIZE / ATLAS_H
        f.write(f"    {{ {int(u0*65536)}, {int(v0*65536)}, {int(u1*65536)}, {int(v1*65536)} }},  /* {name} */\n")
    f.write("};\n\n")

    # Atlas pixel data
    f.write(f"static const unsigned char g_emojiAtlasData[{len(bgra)}] = {{\n    ")
    for i, b in enumerate(bgra):
        f.write(f"0x{b:02X}")
        if i < len(bgra)-1: f.write(",")
        if (i+1) % 16 == 0: f.write("\n    ")
    f.write("\n};\n\n#endif /* EMOJI_ATLAS_H */\n")

print(f"[+] Written {OUTPUT_H}  ({ATLAS_W}x{ATLAS_H} BGRA, {len(found)} emoji)")