#ifndef SCENECHAT_FONT_H
#define SCENECHAT_FONT_H
/*---------------------------------------------------------------------------
    font.h -- Font atlas texture loader and glyph renderer for SceneChat.

    Uses the pre-baked font_atlas.h generated by gen_atlas.py.
    Three sizes: SMALL (14px), MEDIUM (18px), LARGE (24px).

    Call order:
        Font_Init(pDevice)    -- call once after D3D8 device created
        Font_Shutdown()       -- call on device release
        Font_DrawText(...)    -- call during scene render
---------------------------------------------------------------------------*/

#include <xtl.h>
#include <d3d8.h>

#ifdef __cplusplus
extern "C" {
#endif

    /* Font size indices */
#define FONT_SIZE_SMALL    0
#define FONT_SIZE_MEDIUM   1
#define FONT_SIZE_LARGE    2

/* Colour packing helper -- ARGB */
#define FONT_RGBA(r,g,b,a) (((DWORD)(a)<<24)|((DWORD)(r)<<16)|((DWORD)(g)<<8)|(DWORD)(b))
#define FONT_WHITE          FONT_RGBA(255,255,255,255)
#define FONT_GREEN          FONT_RGBA( 57,255, 20,255)   /* #39FF14 SceneChat green  */
#define FONT_PURPLE         FONT_RGBA(139, 92,246,255)   /* #8B5CF6 SceneChat purple */
#define FONT_GRAY           FONT_RGBA(170,170,170,255)
#define FONT_DARKGRAY       FONT_RGBA( 80, 80, 80,255)
#define FONT_BLACK          FONT_RGBA(  0,  0,  0,255)
#define FONT_RED            FONT_RGBA(220, 50, 50,255)

/* Initialise -- uploads atlas texture to GPU.
   Must be called after IDirect3DDevice8 is created. */
    int  Font_Init(IDirect3DDevice8* pDevice);
    void Font_Shutdown(void);

    /* Measure a string without drawing it.
       Returns pixel width; height is always the glyph height for that size. */
    int  Font_MeasureText(const char* str, int size);
    int  Font_GlyphHeight(int size);

    /* Draw a string at screen position (x, y).
       size   = FONT_SIZE_SMALL / MEDIUM / LARGE
       colour = ARGB packed DWORD (use FONT_* macros above)
       max_w  = clip width in pixels (0 = no clip) */
    void Font_DrawText(IDirect3DDevice8* pDevice,
        float x, float y,
        const char* str,
        int size,
        DWORD colour,
        int max_w);

    /* Draw text centred horizontally within a rectangle */
    void Font_DrawTextCentered(IDirect3DDevice8* pDevice,
        float cx, float y,
        float width,
        const char* str,
        int size,
        DWORD colour);

    /* Draw text right-aligned to x */
    void Font_DrawTextRight(IDirect3DDevice8* pDevice,
        float x, float y,
        const char* str,
        int size,
        DWORD colour);

#ifdef __cplusplus
}
#endif

#endif /* SCENECHAT_FONT_H */